services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=hrenelli
      - POSTGRES_PASSWORD=hrenelli
      - POSTGRES_DB=hrenelli
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local